// Konten Panduan Penggunaan (PND-01, PND-02). Disimpan di repo agar mudah diubah tanpa migrasi.
export const GUIDE_STEPS = [
  {
    key: "atur_pernikahan",
    title: "Atur pernikahan",
    body: "Isi tanggal pernikahan, kota, dan daftar acara seperti akad dan resepsi. Tanggal ini dipakai untuk menghitung due date checklist dan hitung mundur.",
    path: "pengaturan?tab=acara",
    cta: "Buka Pengaturan",
    rule: "Tanggal pernikahan terisi dan minimal 1 acara tercatat",
  },
  {
    key: "tentukan_budget",
    title: "Tentukan budget",
    body: "Sepakati total budget, lalu bagi ke kategori seperti venue, katering, dan dekorasi. Peringatan muncul bila realisasi melebihi alokasi.",
    path: "budget",
    cta: "Buka Budgeting",
    rule: "Total budget terisi dan minimal 1 kategori punya alokasi",
  },
  {
    key: "rapikan_checklist",
    title: "Rapikan checklist",
    body: "Checklist rekomendasi sudah disiapkan per fase. Hapus yang tidak relevan, tambahkan tugas kalian sendiri, dan tentukan penanggung jawab.",
    path: "checklist",
    cta: "Buka Checklist",
    rule: "Minimal 1 tugas sudah selesai",
  },
  {
    key: "catat_vendor",
    title: "Catat vendor",
    body: "Simpan vendor yang sedang dilirik beserta paketnya. Saat deal, item budget serta jadwal DP dan pelunasan bisa dibuat otomatis.",
    path: "vendor",
    cta: "Buka Kelola Vendor",
    rule: "Minimal 1 vendor tercatat",
  },
  {
    key: "daftar_tamu",
    title: "Masukkan daftar tamu",
    body: "Tambahkan tamu satu per satu atau impor dari Excel. Nomor WhatsApp otomatis dirapikan dan duplikat terdeteksi.",
    path: "tamu",
    cta: "Buka Tamu & RSVP",
    rule: "Minimal 1 tamu tercatat",
  },
  {
    key: "template_whatsapp",
    title: "Siapkan template WhatsApp",
    body: "Sesuaikan pesan undangan. Placeholder seperti {nama_tamu} dan {link_rsvp} terisi otomatis untuk setiap tamu.",
    path: "tamu",
    cta: "Atur Template",
    rule: "Template pernah diubah atau minimal 1 undangan dikirim",
  },
  {
    key: "susun_rundown",
    title: "Susun rundown",
    body: "Buat susunan acara per sesi lengkap dengan PIC dan lokasi, lalu cetak untuk keluarga dan vendor.",
    path: "rundown",
    cta: "Buka Rundown",
    rule: "Minimal 1 kegiatan di rundown",
  },
  {
    key: "lengkapi_dokumen",
    title: "Lengkapi dokumen",
    body: "Centang dokumen administrasi yang sudah siap dan simpan salinannya di penyimpanan privat.",
    path: "dokumen",
    cta: "Buka Dokumen",
    rule: "Semua checklist administrasi tercentang",
  },
] as const;
